export const UPLOAD_AVATAR_REQUEST = 'UPLOAD_AVATAR_REQUEST' as const;
export const UPLOAD_AVATAR_SUCCESS = 'UPLOAD_AVATAR_SUCCESS' as const;
export const UPLOAD_AVATAR_FAILURE = 'UPLOAD_AVATAR_FAILURE' as const;
