export const LOAD_USER_DIARYS_REQUEST = "LOAD_USER_DIARYS_REQUEST";
export const LOAD_USER_DIARYS_SUCCESS = "LOAD_USER_DIARYS_SUCCESS";
export const LOAD_USER_DIARYS_FAILURE = "LOAD_USER_DIARYS_FAILURE";
