export const ADD_DIARY_REQUEST = "ADD_DIARY_REQUEST" as const;
export const ADD_DIARY_SUCCESS = "ADD_DIARY_SUCCESS" as const;
export const ADD_DIARY_FAILURE = "ADD_DIARY_FAILURE" as const;
export const ADD_DIARY_ERROR_FINISH = "ADD_DIARY_ERROR_FINISH" as const;

export const REMOVE_DIARY_REQUEST = "REMOVE_DIARY_REQUEST" as const;
export const REMOVE_DIARY_SUCCESS = "REMOVE_DIARY_SUCCESS" as const;
export const REMOVE_DIARY_FAILURE = "REMOVE_DIARY_FAILURE" as const;

export const UPLOAD_PHOTOS_REQUEST = "UPLOAD_PHOTOS_REQUEST" as const;
export const UPLOAD_PHOTOS_SUCCESS = "UPLOAD_PHOTOS_SUCCESS" as const;
export const UPLOAD_PHOTOS_FAILURE = "UPLOAD_PHOTOS_FAILURE" as const;

export const REMOVE_DIARY_PHOTO = "REMOVE_DIARY_PHOTO" as const;

export const BACK_TO_DIARY = "BACK_TO_DIARY" as const;
export const BACK_TO_DIARY_FINISH = "BACK_TO_DIARY_FINISH" as const;

export const LOAD_FEEL_DIARYS_REQUEST = "LOAD_FEEL_DIARYS_REQUEST" as const;
export const LOAD_FEEL_DIARYS_SUCCESS = "LOAD_FEEL_DIARYS_SUCCESS" as const;
export const LOAD_FEEL_DIARYS_FAILURE = "LOAD_FEEL_DIARYS_FAILURE" as const;
