export const LOAD_USER_DIARYS_REQUEST = "LOAD_USER_DIARYS_REQUEST";
export const LOAD_USER_DIARYS_SUCCESS = "LOAD_USER_DIARYS_SUCCESS";
export const LOAD_USER_DIARYS_FAILURE = "LOAD_USER_DIARYS_FAILURE";

export const LOAD_SINGLE_DIARY_REQUEST = "LOAD_SINGLE_DIARY_REQUEST";
export const LOAD_SINGLE_DIARY_SUCCESS = "LOAD_SINGLE_DIARY_SUCCESS";
export const LOAD_SINGLE_DIARY_FAILURE = "LOAD_SINGLE_DIARY_FAILURE";

export const ADD_DIARY_REQUEST = "ADD_DIARY_REQUEST";
export const ADD_DIARY_SUCCESS = "ADD_DIARY_SUCCESS";
export const ADD_DIARY_FAILURE = "ADD_DIARY_FAILURE";

export const REMOVE_DIARY_REQUEST = "REMOVE_DIARY_REQUEST";
export const REMOVE_DIARY_SUCCESS = "REMOVE_DIARY_SUCCESS";
export const REMOVE_DIARY_FAILURE = "REMOVE_DIARY_FAILURE";

export const UPLOAD_PHOTOS_REQUEST = "UPLOAD_PHOTOS_REQUEST";
export const UPLOAD_PHOTOS_SUCCESS = "UPLOAD_PHOTOS_SUCCESS";
export const UPLOAD_PHOTOS_FAILURE = "UPLOAD_PHOTOS_FAILURE";

export const REMOVE_DIARY_PHOTO = "REMOVE_DIARY_PHOTO";

export const BACK_TO_DIARY = "BACK_TO_DIARY";
export const BACK_TO_DIARY_FINISH = "BACK_TO_DIARY_FINISH";

export const LOAD_FEEL_DIARYS_REQUEST = "LOAD_FEEL_DIARYS_REQUEST";
export const LOAD_FEEL_DIARYS_SUCCESS = "LOAD_FEEL_DIARYS_SUCCESS";
export const LOAD_FEEL_DIARYS_FAILURE = "LOAD_FEEL_DIARYS_FAILURE";
