export const LOAD_USER_DIARYS_REQUEST = "LOAD_USER_DIARYS_REQUEST";
export const LOAD_USER_DIARYS_SUCCESS = "LOAD_USER_DIARYS_SUCCESS";
export const LOAD_USER_DIARYS_FAILURE = "LOAD_USER_DIARYS_FAILURE";

export const ADD_DIARY_REQUEST = "ADD_DIARY_REQUEST";
export const ADD_DIARY_SUCCESS = "ADD_DIARY_SUCCESS";
export const ADD_DIARY_FAILURE = "ADD_DIARY_FAILURE";

export const UPLOAD_PHOTOS_REQUEST = "UPLOAD_PHOTOS_REQUEST";
export const UPLOAD_PHOTOS_SUCCESS = "UPLOAD_PHOTOS_SUCCESS";
export const UPLOAD_PHOTOS_FAILURE = "UPLOAD_PHOTOS_FAILURE";

export const REMOVE_DIARY_PHOTO = "REMOVE_DIARY_PHOTO";
