export const LOAD_SINGLE_POST_REQUEST = "LOAD_SINGLE_POST_REQUEST";
export const LOAD_SINGLE_POST_SUCCESS = "LOAD_SINGLE_POST_SUCCESS";
export const LOAD_SINGLE_POST_FAILURE = "LOAD_SINGLE_POST_FAILURE";

export const LOAD_ALL_POST_REQUEST = "LOAD_ALL_POST_REQUEST";
export const LOAD_ALL_POST_SUCCESS = "LOAD_ALL_POST_SUCCESS";
export const LOAD_ALL_POST_FAILURE = "LOAD_ALL_POST_FAILURE";

export const LOAD_USER_ALL_POST_REQUEST = "LOAD_USER_ALL_POST_REQUEST";
export const LOAD_USER_ALL_POST_SUCCESS = "LOAD_USER_ALL_POST_SUCCESS";
export const LOAD_USER_ALL_POST_FAILURE = "LOAD_USER_ALL_POST_FAILURE";

export const LOAD_HASHTAG_POSTS_REQUEST = "LOAD_HASHTAG_POSTS_REQUEST";
export const LOAD_HASHTAG_POSTS_SUCCESS = "LOAD_HASHTAG_POSTS_SUCCESS";
export const LOAD_HASHTAG_POSTS_FAILURE = "LOAD_HASHTAG_POSTS_FAILURE";

export const ADD_POST_REQUEST = "ADD_POST_REQUEST";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAILURE = "ADD_POST_FAILURE";

export const REMOVE_POST_REQUEST = "REMOVE_POST_REQUEST";
export const REMOVE_POST_SUCCESS = "REMOVE_POST_SUCCESS";
export const REMOVE_POST_FAILURE = "REMOVE_POST_FAILURE";

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAILURE = "UPDATE_POST_FAILURE";

export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAILURE = "LIKE_POST_FAILURE";

export const UNLIKE_POST_REQUEST = "UNLIKE_POST_REQUEST";
export const UNLIKE_POST_SUCCESS = "UNLIKE_POST_SUCCESS";
export const UNLIKE_POST_FAILURE = "UNLIKE_POST_FAILURE";

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILURE = "ADD_COMMENT_FAILURE";

export const UPLOAD_IMAGES_REQUEST = "UPLOAD_IMAGES_REQUEST";
export const UPLOAD_IMAGES_SUCCESS = "UPLOAD_IMAGES_SUCCESS";
export const UPLOAD_IMAGES_FAILURE = "UPLOAD_IMAGES_FAILURE ";

export const REPOST_REQUEST = "REPOST_REQUEST";
export const REPOST_SUCCESS = "REPOST_SUCCESS";
export const REPOST_FAILURE = "REPOST_FAILURE ";
export const REPOST_ERROR_FINISH = "REPOST_ERROR_FINISH";

export const REMOVE_IMAGE = "REMOVE_IMAGE";
