export const LOAD_SINGLE_POST_REQUEST = "LOAD_SINGLE_POST_REQUEST" as const;
export const LOAD_SINGLE_POST_SUCCESS = "LOAD_SINGLE_POST_SUCCESS" as const;
export const LOAD_SINGLE_POST_FAILURE = "LOAD_SINGLE_POST_FAILURE" as const;

export const LOAD_ALL_POST_REQUEST = "LOAD_ALL_POST_REQUEST" as const;
export const LOAD_ALL_POST_SUCCESS = "LOAD_ALL_POST_SUCCESS" as const;
export const LOAD_ALL_POST_FAILURE = "LOAD_ALL_POST_FAILURE" as const;

export const LOAD_USER_ALL_POST_REQUEST = "LOAD_USER_ALL_POST_REQUEST" as const;
export const LOAD_USER_ALL_POST_SUCCESS = "LOAD_USER_ALL_POST_SUCCESS" as const;
export const LOAD_USER_ALL_POST_FAILURE = "LOAD_USER_ALL_POST_FAILURE" as const;

export const LOAD_RELATED_POSTS_REQUEST = "LOAD_RELATED_POSTS_REQUEST" as const;
export const LOAD_RELATED_POSTS_SUCCESS = "LOAD_RELATED_POSTS_SUCCESS" as const;
export const LOAD_RELATED_POSTS_FAILURE = "LOAD_RELATED_POSTS_FAILURE" as const;

export const LOAD_HASHTAG_POSTS_REQUEST = "LOAD_HASHTAG_POSTS_REQUEST" as const;
export const LOAD_HASHTAG_POSTS_SUCCESS = "LOAD_HASHTAG_POSTS_SUCCESS" as const;
export const LOAD_HASHTAG_POSTS_FAILURE = "LOAD_HASHTAG_POSTS_FAILURE" as const;

export const ADD_POST_REQUEST = "ADD_POST_REQUEST" as const;
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS" as const;
export const ADD_POST_FAILURE = "ADD_POST_FAILURE" as const;
export const ADD_POST_ERROR_FINISH = "ADD_POST_ERROR_FINISH" as const;

export const REMOVE_POST_REQUEST = "REMOVE_POST_REQUEST" as const;
export const REMOVE_POST_SUCCESS = "REMOVE_POST_SUCCESS" as const;
export const REMOVE_POST_FAILURE = "REMOVE_POST_FAILURE" as const;

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST" as const;
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS" as const;
export const UPDATE_POST_FAILURE = "UPDATE_POST_FAILURE" as const;

export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST" as const;
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS" as const;
export const LIKE_POST_FAILURE = "LIKE_POST_FAILURE" as const;

export const UNLIKE_POST_REQUEST = "UNLIKE_POST_REQUEST" as const;
export const UNLIKE_POST_SUCCESS = "UNLIKE_POST_SUCCESS" as const;
export const UNLIKE_POST_FAILURE = "UNLIKE_POST_FAILURE" as const;

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST" as const;
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS" as const;
export const ADD_COMMENT_FAILURE = "ADD_COMMENT_FAILURE" as const;

export const UPLOAD_IMAGES_REQUEST = "UPLOAD_IMAGES_REQUEST" as const;
export const UPLOAD_IMAGES_SUCCESS = "UPLOAD_IMAGES_SUCCESS" as const;
export const UPLOAD_IMAGES_FAILURE = "UPLOAD_IMAGES_FAILURE " as const;

export const REPOST_REQUEST = "REPOST_REQUEST" as const;
export const REPOST_SUCCESS = "REPOST_SUCCESS" as const;
export const REPOST_FAILURE = "REPOST_FAILURE " as const;
export const REPOST_ERROR_FINISH = "REPOST_ERROR_FINISH" as const;

export const REMOVE_IMAGE = "REMOVE_IMAGE" as const;
